language: node_js

node_js:
- "4.5.0"

notifications:
  email:
    - rraavi@indiana.edu

branches:
  only:
    - feature/feature-15-run-weather-forecast

sudo: true

before_install:
- cd core/javascript/runWeatherForecast/

install:
- npm install
