language: node_js

node_js:
- "4.5.0"

notifications:
  email:
    - rraavi@indiana.edu

branches:
  only:
    - feature/feature-15-run-weather-forecast

sudo: true

before_install:
- cd core/javascript/runWeatherForecast/

install:
- npm install

before_deploy:
  - cd ..
  - zip -r RunWeatherForecast.zip runWeatherForecast || true
  - mkdir -p "dpl_cd_upload"
  - mv RunWeatherForecast.zip dpl_cd_upload/RunWeatherForecast.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-bash
    local_dir: dpl_cd_upload
    region: US Standard
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-15-run-weather-forecast
